image::https://travis-ci.org/spring-cloud/spring-cloud-zookeeper.svg?branch=master[Build Status, link=https://travis-ci.org/spring-cloud/spring-cloud-zookeeper]

include::intro.adoc[]

== Zookeeper overview

ZooKeeper is a centralized service for maintaining configuration information, naming,
providing distributed synchronization, and providing group services. See the
http://zookeeper.apache.org[Zookeeper site] for more information. Spring Cloud Zookeeper
also builds on the http://curator.apache.org[Apache Curator] project, which started life
at Netflix.

== Spring Cloud Zookeeper Features

Spring Cloud Zookeeper includes the following features:

* Spring Cloud `DiscoveryClient` implementation (supports Ribbon and Zuul)
* Zookeeper-based `PropertySource` loaded during the 'bootstrap' phase

== Running the Sample

. http://zookeeper.apache.org/doc/current/zookeeperStarted.html#sc_Download[Install
zookeeper] (On a mac with homebrew, use `brew install zookeeper`).
. http://zookeeper.apache.org/doc/current/zookeeperStarted.html#sc_InstallingSingleMode[Start
zookeeper].
. http://zookeeper.apache.org/doc/current/zookeeperStarted.html#sc_ConnectingToZooKeeper[Verify
zookeeper is running].
. Run `mvn --settings .settings.xml package`.
Doing so brings in the required Spring Cloud Maven repositories and Build.
. Run `java -jar spring-cloud-zookeeper-sample/target/spring-cloud-zookeeper-sample-1.2.0.BUILD-SNAPSHOT.jar`.
. Visit http://localhost:8080 to verify that `{"serviceId":"testZookeeperApp","host":"<yourhost>","port":8080}` works.
. Run `java -jar spring-cloud-zookeeper-sample/target/spring-cloud-zookeeper-sample-1.2.0.BUILD-SNAPSHOT.jar --server.port=8081`
. Visit http://localhost:8080 again to verify that `{"serviceId":"testZookeeperApp","host":"<yourhost>","port":8081}` eventually shows up in the results in a round-robin fashion. (It may take a minute or so.)

== Building

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building.adoc[]

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
